### ISSUE TITLE
Base.pkl file is missing while trying to use MSP60k

### ISSUE THREAD

**Issue by asad1416** [Event-AHU/OpenPAR#28]
I am trying to train model with MSP60k but it gives that .pkl file missing. I figure out that I have to generate file using .py files. But Now I am stuck it is asking base.pkl file which is not present in whole directory. Please guide a step step approach to make this dataset ready for training.

 split_1
Traceback (most recent call last):
  File "/UNITY-NFS/Data_B/OpenPAR/SUBMIT/msp_withMS.py", line 141, in <module>
    generate_pkl_MS(save_dir, exist_pkl_path=exist_pkl_path, only_change_root=False)
  File "/UNITY-NFS/Data_B/OpenPAR/SUBMIT/msp_withMS.py", line 99, in generate_pkl_MS
    exist_pkl = pickle.load(open(exist_pkl_path, 'rb+'))
FileNotFoundError: [Errno 2] No such file or directory: '/UNITY-NFS/Data_B/OpenPAR/SUBMIT/split/base.pkl'

**Comment by asad1416** [comment]
Currently the dataset have 3 .pkl files  dataset_random.pkl, dataset_ms_split1.pkl and dataset_ms_split2.pkl. I tried all three files giving in local.py. But I am getting follwing error 
File "/UNITY-NFS/Data_B/OpenPAR/MSP60K_Benchmark_Dataset/LLM-PAR/train.py", line 261, in <module>
    main(args)
  File "/UNITY-NFS/Data_B/OpenPAR/MSP60K_Benchmark_Dataset/LLM-PAR/train.py", line 30, in main
    train_set = MultiModalAttrDataset(args=args, split=args.train_split, transform=train_tsfm) #得到训练数据集
  File "/UNITY-NFS/Data_B/OpenPAR/MSP60K_Benchmark_Dataset/LLM-PAR/dataset/AttrDataset.py", line 36, in __init__
    self.sentences = dataset_info.sentences
AttributeError: 'EasyDict' object has no attribute 'sentences'

**Comment by 1125178969** [comment]
if you want run the LLMPAR, you need generate the `Template.pkl` use the scripts for the corresponding dataset in `MSP60K_Benchmark_Dataset/LLM-PAR/PAR_Template_Scripts`

**Comment by 1125178969** [comment]
https://github.com/Event-AHU/OpenPAR/issues/28#issue-2512900555
you can set the `exist_pkl_path `as `None`
